apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test-1
  labels:
    app: app-test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-test-1
  template:
    metadata:
      labels:
        app: app-test-1
    spec:
      containers:
      - name: app-test-1
        image: diegokraenau/app-test-1
        ports:
        - containerPort: 3000